# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - areumii_arm_l_controller
    - areumii_arm_r_controller
    - areumii_gripper_l_controller
    - areumii_gripper_r_controller

  areumii_arm_l_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch_joint_L
      - shoulder_roll_joint_L
      - shouler_yaw_joint_L
      - elbow_joint_L
      - wrist_roll_joint_L
      - wrist_yaw_joint_L
      - wrist_pitch_joint_L
    action_ns: follow_joint_trajectory
    default: true
  areumii_arm_r_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch_joint_R
      - shoulder_roll_joint_R
      - shoulder_yaw_joint_R
      - elbow_joint_R
      - wrist_roll_joint_R
      - wrist_yaw_joint_R
      - wrist_pitch_joint_R
    action_ns: follow_joint_trajectory
    default: true
  areumii_gripper_l_controller:
    type: GripperCommand
    joints:
      - gripper_left_finger_joint_L
    action_ns: gripper_cmd
    default: true
  areumii_gripper_r_controller:
    type: GripperCommand
    joints:
      - gripper_left_finger_joint_R
    action_ns: gripper_cmd
    default: true